package model

import (
	"github.com/easy-model-fusion/emf-cli/internal/codegen"
	"github.com/easy-model-fusion/emf-cli/pkg/huggingface"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
	"strings"
)

// GetFormattedModelName format the model name in CapsWord start with "Model"
func (m *Model) GetFormattedModelName() string {
	return strings.Join([]string{
		"Model",
		strings.ReplaceAll(strings.ReplaceAll(
			cases.Title(language.English, cases.Compact).String(m.Name),
			"-", ""),
			"/", ""),
	}, "")
}

// GetSDKClassNameWithModule return the sdk model for the given model
func (m *Model) GetSDKClassNameWithModule() string {
	switch m.Module {
	case huggingface.DIFFUSERS:
		return huggingface.SDKModelDiffusers
	case huggingface.TRANSFORMERS:
		return huggingface.SDKModelTransformers
	default:
		return ""
	}
}

// GetHuggingFaceClassImport Get hugging face class for the import
func (m *Model) GetHuggingFaceClassImport() string {
	switch m.Module {
	case huggingface.DIFFUSERS:
		return m.Class
	case huggingface.TRANSFORMERS:
		return strings.Join([]string{m.Class, m.Tokenizers[0].Class}, ", ")
	default:
		return ""
	}
}

// GetModuleAutoPipelineClassName return the auto pipeline for the given model
func (m *Model) GetModuleAutoPipelineClassName() string {
	switch m.Module {
	case huggingface.DIFFUSERS:
		return huggingface.AutoDiffusers
	case huggingface.TRANSFORMERS:
		return huggingface.AutoTransformers
	default:
		return ""
	}
}

// GenFile generates a single python file for the given model
func (m *Model) GenFile() *codegen.File {
	return &codegen.File{
		Name: m.GetFormattedModelName() + ".py",
		HeaderComments: []string{
			"Code generated by EMF",
			"DO NOT EDIT!",
		},
		Imports: m.GenImports(),
		Classes: []*codegen.Class{
			m.GenClass(),
		},
	}
}

// GenImports generate the imports for the given model
func (m *Model) GenImports() []codegen.Import {
	return []codegen.Import{
		{
			What: []codegen.ImportWhat{
				{
					Name: m.GetSDKClassNameWithModule(),
				},
			},
			From: "sdk.models",
		},
		{
			What: []codegen.ImportWhat{
				{
					Name: "Devices",
				},
			},
			From: "sdk.options",
		},
		{
			What: []codegen.ImportWhat{
				{
					Name: m.GetHuggingFaceClassImport(),
				},
			},
			From: string(m.Module),
		},
	}
}

// GenInitParamsWithModule generate the init params for the given model
func (m *Model) GenInitParamsWithModule() []codegen.Parameter {
	switch m.Module {
	case huggingface.DIFFUSERS:
		return []codegen.Parameter{
			{
				Name: "self",
			},
			{
				Name: "**kwargs",
			}}

	case huggingface.TRANSFORMERS:
		return []codegen.Parameter{
			{
				Name: "self",
			}}

	default:
		return []codegen.Parameter{}
	}
}

// GenSuperInitParamsWithModule generate the init params for the super class
func (m *Model) GenSuperInitParamsWithModule() []codegen.FunctionCallParameter {

	switch m.Module {
	case huggingface.DIFFUSERS:
		return []codegen.FunctionCallParameter{
			{
				Name:  "model_name",
				Value: "\"" + m.Name + "\"",
			},
			{
				Name:  "model_path",
				Value: "\"" + m.Path + "\"",
			},
			{
				Name:  "model_class",
				Value: m.Class,
			},
			{
				Name:  "device",
				Value: "Devices.GPU",
			}, /*, ToDo : Add the Kwargs to the generation
			{
				Value: "**kwargs",
			}*/}

	case huggingface.TRANSFORMERS:
		return []codegen.FunctionCallParameter{
			{
				Name:  "model_name",
				Value: "\"" + m.Name + "\"",
			},
			{
				Name:  "model_path",
				Value: "\"" + m.Path + "\"",
			},
			{
				Name:  "tokenizer_path",
				Value: "\"" + m.Tokenizers[0].Path + "\"",
			},
			{
				Name:  "task",
				Value: "\"" + string(m.PipelineTag) + "\"",
			},
			{
				Name:  "model_class",
				Value: m.Class,
			},
			{
				Name:  "tokenizer_class",
				Value: m.Tokenizers[0].Class,
			},
			{
				Name:  "device",
				Value: "Devices.GPU",
			}}

	default:
		return []codegen.FunctionCallParameter{}
	}
}

func (m *Model) GenClass() *codegen.Class {
	return &codegen.Class{
		Name:   m.GetFormattedModelName(),
		Extend: m.GetSDKClassNameWithModule(),
		Methods: []*codegen.Function{
			{
				Name:   "__init__",
				Params: m.GenInitParamsWithModule(),
				Body: []codegen.Statement{
					&codegen.FunctionCallStmt{
						FunctionCall: codegen.FunctionCall{
							Name:   "super().__init__",
							Params: m.GenSuperInitParamsWithModule(),
						},
					},
				},
			},
		},
	}
}
